package com.umg.sgq.enumeracion;
public enum CodigoPermiso {
    CASE_VIEW, CASE_UPDATE, CASE_ASSIGN, CASE_FOLLOWUP, CASE_RESOLVE, CASE_CLOSE, CASE_REOPEN, CASE_PRIORITY,
    EVIDENCE_UPLOAD, EVIDENCE_DOWNLOAD, USER_ADMIN, ROLE_ADMIN, BRANCH_ADMIN, REPORT_VIEW, REPORT_EXPORT,
    AUDIT_VIEW, AUDIT_EXPORT, NOTIFICATION_ADMIN
}
