package com.umg.sgq.enumeracion;
public enum EventoNotificacion { REGISTRO_CASO, ASIGNACION, REASIGNACION, SOLICITUD_INFORMACION, SEGUIMIENTO_VISIBLE, CAMBIO_RESUELTO, CIERRE, RECHAZO, SLA_80, SLA_VENCIDO, ESCALAMIENTO_CRITICO }
